/*
* Created by Connel Asikong on 31/03/2026
*
*/

// The core data model for an atomic swap.
//
// A swap has two sides:
//   initiator (Alice) — creates the offer, locks first
//   counter   (Bob)   — receives the offer, locks second
//
// State machine (happy path):
//   offerSent → initiatorLocked → counterLocked
//             → counterClaimed  → completed
//
// Terminal states: completed, declined, failed, refunded
//
// The secret is generated by Alice and stored locally only.
// The secretHash (SHA256 of secret) travels over Nostr.
// Bob never sees the secret until he claims — at which point
// Alice reveals it on-chain and it becomes public.

import 'package:equatable/equatable.dart';

enum SwapState {
  offerSent,
  initiatorLocked,
  counterLocked,
  counterClaimed,
  completed,
  declined,
  failed,
  refunded,
}

enum Chain { sui, bitcoin }

class SwapOffer extends Equatable {
  const SwapOffer({
    required this.id,
    required this.initiatorPubKey,
    required this.counterPubKey,
    required this.sendTokenId,
    required this.receiveTokenId,
    required this.sendChain,
    required this.receiveChain,
    required this.sendAmount,
    required this.receiveAmount,
    required this.secretHash,
    required this.expiresAt,
    required this.state,
    this.secret,
    this.sealWrappedSecret,
    this.initiatorTxHash,
    this.counterTxHash,
    this.walrusBlobId,
  });

  final String id;
  final String initiatorPubKey;
  final String counterPubKey;
  final String sendTokenId; // 'SUI', 'BTC', 'USDC', 'USDT'
  final String receiveTokenId;
  final Chain sendChain;
  final Chain receiveChain;
  final BigInt sendAmount; // smallest unit (MIST / satoshi)
  final BigInt receiveAmount;
  final String secretHash; // SHA256(secret) hex — goes on-chain
  final int expiresAt; // Unix timestamp seconds
  final SwapState state;

  // Populated as swap progresses
  final String? secret; // Alice only — never sent over Nostr
  final String? sealWrappedSecret; // Seal-encrypted blob — sent in offer
  final String? initiatorTxHash; // on-chain lock tx
  final String? counterTxHash; // on-chain lock tx
  final String? walrusBlobId; // receipt stored on Walrus

  bool get isTerminal =>
      state == SwapState.completed ||
      state == SwapState.declined ||
      state == SwapState.failed ||
      state == SwapState.refunded;

  bool get isExpired =>
      DateTime.now().millisecondsSinceEpoch ~/ 1000 > expiresAt;

  SwapOffer copyWith({
    SwapState? state,
    String? secret,
    String? sealWrappedSecret,
    String? initiatorTxHash,
    String? counterTxHash,
    String? walrusBlobId,
  }) {
    return SwapOffer(
      id: id,
      initiatorPubKey: initiatorPubKey,
      counterPubKey: counterPubKey,
      sendTokenId: sendTokenId,
      receiveTokenId: receiveTokenId,
      sendChain: sendChain,
      receiveChain: receiveChain,
      sendAmount: sendAmount,
      receiveAmount: receiveAmount,
      secretHash: secretHash,
      expiresAt: expiresAt,
      state: state ?? this.state,
      secret: secret ?? this.secret,
      sealWrappedSecret: sealWrappedSecret ?? this.sealWrappedSecret,
      initiatorTxHash: initiatorTxHash ?? this.initiatorTxHash,
      counterTxHash: counterTxHash ?? this.counterTxHash,
      walrusBlobId: walrusBlobId ?? this.walrusBlobId,
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'initiatorPubKey': initiatorPubKey,
    'counterPubKey': counterPubKey,
    'sendTokenId': sendTokenId,
    'receiveTokenId': receiveTokenId,
    'sendChain': sendChain.name,
    'receiveChain': receiveChain.name,
    'sendAmount': sendAmount.toString(),
    'receiveAmount': receiveAmount.toString(),
    'secretHash': secretHash,
    'expiresAt': expiresAt,
    'state': state.name,
    'secret': secret,
    'sealWrappedSecret': sealWrappedSecret,
    'initiatorTxHash': initiatorTxHash,
    'counterTxHash': counterTxHash,
    'walrusBlobId': walrusBlobId,
  };

  factory SwapOffer.fromJson(Map<String, dynamic> json) => SwapOffer(
    id: json['id'] as String,
    initiatorPubKey: json['initiatorPubKey'] as String,
    counterPubKey: json['counterPubKey'] as String,
    sendTokenId: json['sendTokenId'] as String,
    receiveTokenId: json['receiveTokenId'] as String,
    sendChain: Chain.values.byName(json['sendChain'] as String),
    receiveChain: Chain.values.byName(json['receiveChain'] as String),
    sendAmount: BigInt.parse(json['sendAmount'] as String),
    receiveAmount: BigInt.parse(json['receiveAmount'] as String),
    secretHash: json['secretHash'] as String,
    expiresAt: json['expiresAt'] as int,
    state: SwapState.values.byName(json['state'] as String),
    secret: json['secret'] as String?,
    sealWrappedSecret: json['sealWrappedSecret'] as String?,
    initiatorTxHash: json['initiatorTxHash'] as String?,
    counterTxHash: json['counterTxHash'] as String?,
    walrusBlobId: json['walrusBlobId'] as String?,
  );

  @override
  List<Object?> get props => [];
}
